spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev222
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test
