spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  profiles: test111
  application:
    name: microservicecloud-config-atguigu-test
